### ISSUE TITLE
traing space

### ISSUE THREAD

**Issue by zhw-zhang** [DQiaole/FlowDiffusion_pytorch#2]
Hello, may I ask why you trained directly on pixel space instead of training on latent space like stable diffusion. Training on latent space will save more computing resources and save GPU memory.

**Comment by DQiaole** [comment]
Hi, thanks. Training on latent space could be a promising idea. But we may need first to train an auto-encoder for optical flow on large-scale optical flow datasets. To ease the data scarcity of optical flow and warm up the training, the original paper of DDVM utilizes the pre-trained weight from Palette, which is also trained on pixel space. Besides, incorporating more task-specific priors/designs for optical flow estimation can also save computing resources, as we have done here, i.e., introducing the cost volume.
