### ISSUE TITLE
training problem

### ISSUE THREAD

**Issue by happydummy** [DQiaole/FlowDiffusion_pytorch#3]
thanks for your work!
when i reproduce your work ,I meet this promblem, is this normal?
![screenshot-20240826-155212](https://github.com/user-attachments/assets/7c589c75-a402-4e33-8659-13d8a1e9347a)

**Comment by DQiaole** [comment]
Hi, this is normal, which may be caused by the mixed precision we used. When loss exploding, we can resume the model from one recent normal checkpoints and continue training.

**Comment by ccj5351** [comment]
Thanks for creating this question. I also met this problem with the deepSteep training. By the way, have you used the DeepSteep training for this plot/curve?

**Comment by happydummy** [comment]
> Thanks for creating this question. I also met this problem with the deepSteep training. By the way, have you used the DeepSteep training for this plot/curve?

yes, it's normal with mixed precision setting
